---
# Component with both GitHub and Jira Scorecards
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: all-scorecards
  annotations:
    github.com/project-slug: djanickova/overlay-scorecard-plugin-test
    backstage.io/source-location: url:https://github.com/djanickova/overlay-scorecard-plugin-test/tree/add-readme-test
    jira/project-key: RSPT
    openssf/scorecard-location: https://api.securityscorecards.dev/projects/github.com/ossf/scorecard
    scorecard.io/disabled-metrics: openssf.maintained
spec:
  type: service
  owner: user:test1
  lifecycle: production
